### PR TITLE
suppress warning for generated Connext code

### PR DESCRIPTION
**Pull request by dirk-thomas**
This will fix the following compiler warnings: http://ci.ros2.org/job/ci_linux/1051/warnings17Result/category.-2074711528/

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The second commit fixes the following compiler warning: http://ci.ros2.org/job/ci_linux/1050/warnings17Result/

**Comment by wjwwood** [comment]
lgtm. Should we be doing CI, or are we just going to merge each proposed fix and do a CI at the end of the sprint?

**Comment by dirk-thomas** [comment]
I ran it locally before and after which fixed the compiler warning. So I would propose to merge and run a CI afterwards to also cover other changes merged in the meantime and keep the load on the farm low.

**Comment by dirk-thomas** [comment]
Two generators, same in both. Committed f645b9bd1d3cdb342ba5d51df9c46830eddff19b

**Comment by jacquelinekay** [comment]
why do the strict-aliasing warnings still appear in the Release build?

http://ci.ros2.org/view/nightly/job/nightly_linux_release/1/warnings17Result/new/package.-530164750/

**Comment by dirk-thomas** [comment]
This PR only modified `rosidl_typesupport_connext_c`. The same fix is needed for `rosidl_typesupport_connext_cpp`.

Based on my previous comment (`Two generators, same in both`) I am pretty sure it was changed for both at some point. Anyway this is the follow up PR: #146

**Pull request merged**
