### PR TITLE
compare typesupport identifier symbols instead of strings

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connects to ros2/ros2#30.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Finally ready for review. Windows slave was able to build this: http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_test_windows/15/

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
+1

**Pull request merged**
