### PR TITLE
fix dynamic client

### PR DESCRIPTION
**Pull request by dirk-thomas**
While this disables some cleanup it makes ros2/rclcpp#192 pass. Since rmw_connext (static) does not implement any server / client destroy functionality I just added a todo for this case. I also added a comment for this in the existing ticket: ros2/rmw_connext#63

* http://ci.ros2.org/job/ci_linux/981/
* http://ci.ros2.org/job/ci_osx/815/

### CODE REVIEW

**Comment by tfoote** [comment]
This looks a bit hacky but if it gets the unit tests passing and we've ticketed the fixes I guess it's ok.

**Comment by gerkey** [comment]
Were you able to determine whether this change leaks memory when service clients are repeatedly created and destroyed?

Also, what's the reason for taking out the qos arg?

**Comment by dirk-thomas** [comment]
I am pretty sure that it will not free the memory. I can't tell of the participant would clean it up at the end though.

The `create_type_code` functions simply doesn't use the argument. So no need to pass it.

**Comment by gerkey** [comment]
Good enough, at least for now. +1

**Pull request merged**
