### PR TITLE
Updated error returns on rmw_publish to comply with documentation

### PR DESCRIPTION
**Pull request by Lobotuerk**
Signed-off-by: lobotuerk <jtlorente@ekumenlabs.com>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Review by Blast545 — APPROVED** [review]

**Review by hidmic — COMMENTED** [review]
My only comment is, consider using the appropriate macros (`RMW_CHECK_FOR_NULL_WITH_MSG`, `RMW_CHECK_TYPE_IDENTIFIERS_MATCH`) instead.

**Review by clalancette — APPROVED** [review]

**Review by hidmic — APPROVED** [review]
LGTM pending green CI

**Comment by Lobotuerk** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12275/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7249/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9993/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12166/)

**Comment by Lobotuerk** [comment]
RTI Connext isn't available on arm64 machines, so linux-aarch64 test are disregarded

**Pull request merged**
