### PR TITLE
Use rpputils::find_and_replace instead of std::regex_replace

### PR DESCRIPTION
**Pull request by jacobperron**
The rcpputils implementation is more performant.

Related to https://github.com/ros2/rmw_fastrtps/issues/277
Requires https://github.com/ros2/rcpputils/pull/13

### CODE REVIEW

**Comment by jacobperron** [comment]
> Need ament_export_dependencies(rcpputils)?

Done in 216445d

**Comment by sloretz** [comment]
> >    Need ament_export_dependencies(rcpputils)?
> 
> Done in 216445d

Oops, I missed that `rcpputils::find_and_replace` is header only. Exporting the dependency wasn't necessary.

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7350/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3515/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6028/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7172/)

**Comment by jacobperron** [comment]
> Oops, I missed that rcpputils::find_and_replace is header only (edit: and not included in any includes installed by this package). Exporting the dependency wasn't necessary

Reverted.

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7354/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3518/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6031/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7175/)

**Comment by jacobperron** [comment]
After running CI against master (https://github.com/ros2/rmw_opensplice/issues/264#issuecomment-506459958), it looks like the test failures already exist and are related to builds with OpenSplice.

**Comment by dirk-thomas** [comment]
The PR job for this change failed since the dependency hasn't been released yet. As a consequence the dev job is also failing now.

**Pull request merged**
