### PR TITLE
make FindConnext less strict on required vars

### PR DESCRIPTION
**Pull request by wjwwood**
@dirk-thomas @esteve for review.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
lgtm

**Comment by esteve** [comment]
+1

**Comment by dirk-thomas** [comment]
The assumption was that the failed build was due to Docker using "older" Debian Connext packages. The packages have been fixed in the meantime but since they didn't change the name the Docker was using the "outdated" cache.

But after poking Docker (by changing the Dockerfile) the new build (http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/22/) fails with the same error.

**Comment by esteve** [comment]
This now builds with ros2/ros2#41 merged

http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/25/console

**Comment by wjwwood** [comment]
Thanks @esteve

**Comment by dirk-thomas** [comment]
Test results include pub/sub test for all three rmw implementation now :+1:

**Pull request merged**
