### PR TITLE
Update hook to call 5.2 RTI VS2015

### LINKED ISSUE #80: Update the hook to call 5.2 VS2015
Simple fix to call the 5.2 instead of 5.1

```patch
--- a/connext_cmake_module/env_hook/connext.bat.in
+++ b/connext_cmake_module/env_hook/connext.bat.in
@@ -1,7 +1,7 @@
 set "Connext_HOME=@Connext_HOME@"
 
 :: Call RTI's env setup script, piping stdout to nul, since they have echo on.
-call "%Connext_HOME:/=\%\..\rti_set_env_5.1.0.bat" 1> nul
+call "%Connext_HOME:/=\%\..\rti_set_env_5.2.0.bat" 1> nul
 
 :: Add the Connext_LIBRARY_DIR to the Path so .dll's can be found at runtime.
 set "Connext_LIBRARY_DIR=@Connext_LIBRARY_DIR@"
```

### PR DESCRIPTION
**Pull request by j-rivero**
Same layout used in professional version (ros2/ros2#84) and in my testing release. Note that the professional don't have the VS2015 support yet.

Closes #80

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I don't think the current bat file works. What does `Connext_HOME` point in your case?

**Comment by j-rivero** [comment]
`Connext_HOME` is set to `NDDS_HOME` defined in my version as `C:\Program Files\rti_connext_dds_community-5.2.0osrf\ndds.5.2.0osrf`. The rtisetenv script is at: `C:\Program Files\rti_connext_dds_community-5.2.0osrf\rtisetenv_x64Win64VS2015.bat`

**Comment by dirk-thomas** [comment]
The professional version has it located in `C:\Program Files\rti_connext_dds-5.2.0\resource\scripts`.

**Comment by j-rivero** [comment]
> The professional version has it located in C:\Program Files\rti_connext_dds-5.2.0\resource\scripts.

let me modify my version and fix the pull request

**Comment by dirk-thomas** [comment]
My point is that this bat file currently does not work at all. So updating it for the community edition is not neccessary.

**Comment by dirk-thomas** [comment]
Replaced by #104.

**Pull request closed without merging**
