### PR TITLE
set NDDSUSERDllExport macro to declspec dllimport by default

### PR DESCRIPTION
**Pull request by dirk-thomas**
I have literally no idea why it was building with Connext 5.1 before...

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
This finally works: http://ci.ros2.org/job/ros2_batch_ci_windows/187/

Please take another look since the patch is basicallly entirely different by now :wink:

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Pull request merged**
