### PR TITLE
Fix build error introduced in #368

### PR DESCRIPTION
**Pull request by ivanpauno**
See #368

### CODE REVIEW

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8315/)

**Comment by hidmic** [comment]
@ivanpauno CI complains about not finding `*connext*` packages?

**Comment by ivanpauno** [comment]
Seems to be something random, CI again:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8317/)

**Comment by ivanpauno** [comment]
See https://github.com/ros2/ci/issues/296.
CI again:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8318/)

**Pull request merged**
