### PR TITLE
Fix cmake module for MSVC 2015

### LINKED ISSUE #73: CMake module is not working for MSVC 2015
The [FindConnext.cmake]() was not detecting my home made installation of RTI Connext which mimic the 5.1 and 5.2 RTI official directory layout. I would propose the following patch: 

```patch
diff --git a/connext_cmake_module/cmake/Modules/FindConnext.cmake b/connext_cmake_module/cmake/Modules/FindConnext.cmake
index 6180438..7fb3df5 100644
--- a/connext_cmake_module/cmake/Modules/FindConnext.cmake
+++ b/connext_cmake_module/cmake/Modules/FindConnext.cmake
@@ -166,27 +166,6 @@ if(NOT "${_NDDSHOME} " STREQUAL " ")
     endif()
   endwhile()
 
-  if(_matched_VS2015)
-    set(_i 0)
-    while(TRUE)
-      list(LENGTH _libs _length)
-      if(NOT ${_i} LESS ${_length})
-        break()
-      endif()
-      list(GET _libs ${_i} _lib)
-      set(_match TRUE)
-      string(FIND "${_lib}" "VS2015" _found)
-      if(NOT ${_found} EQUAL -1)
-        set(_match FALSE)
-      endif()
-      if(_match)
-        math(EXPR _i "${_i} + 1")
-      else()
-        list(REMOVE_AT _libs ${_i})
-      endif()
-    endwhile()
-  endif()
-
```

The patch removes an extra check for MSVC2015 which seems not needed to me since the check is already done in [previous code](https://github.com/ros2/rmw_connext/blob/master/connext_cmake_module/cmake/Modules/FindConnext.cmake#L151). And it is particularly buggy in [checking the presence VS2015 string](https://github.com/ros2/rmw_connext/blob/master/connext_cmake_module/cmake/Modules/FindConnext.cmake#L179). Removing the patch worked fine for me in my tests.

### PR DESCRIPTION
**Pull request by j-rivero**
Closes #73. Same content that #74

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by j-rivero** [comment]
* [Failing build](http://ci.ros2.org/job/ros2_batch_ci_windows/240/) with the default branch
* [Passing build](http://ci.ros2.org/job/ros2_batch_ci_windows/247/console#console-section-6) with this branch

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
Why is this "in progress", is there more work to be done or should it be merged?

**Comment by j-rivero** [comment]
> Why is this "in progress", is there more work to be done or should it be merged?

I don't think so.

**Comment by wjwwood** [comment]
Sorry, I don't know which you mean. You don't think there is more work to be done or you don't think it should be merged?

We usually put things back into "in progress" if something comes up during the review process which indicates that it shouldn't be merged.

**Comment by wjwwood** [comment]
I guess you mean it should be merged, since it was never in the "review" column.

**Comment by wjwwood** [comment]
Sorry for the noise.

**Pull request merged**
