### PR TITLE
Make use of DDS namespace instead of DDS_ prefixed versions in global namespace

### PR DESCRIPTION
**Pull request by jwillemsen**
This PR includes the other PRs made last week. Instead of using the DDS_ prefixed versions in the global namespace we are now using the DDS namespace, this simplifies porting and maintaining code between the various rmw_ implementations, see #323

### CODE REVIEW

**Comment by jwillemsen** [comment]
First merge #321 which will solve already some merge conflicts, after that I will recheck

**Comment by sloretz** [comment]
@jwillemsen Mind rebasing this PR?

**Comment by jwillemsen** [comment]
@sloretz I have tried to rebase, but this results in several manual corrections because several changes where in the same area as previous CRs and issues have to be resolved manually. Because of the squash merge the rebase is problematic. Could you maybe just review the changes and ignore the separate commits, at the moment you merge to master everything is squashed also.

**Comment by dirk-thomas** [comment]
The final commit to master is not the only important part. The history of this PR will stay around and it's diff / commits should be viewable for future review to. So please try to rewrite the history to only include actual changes.

**Comment by jwillemsen** [comment]
When looking at the history I got the impression things where squashed, will rebase now

**Comment by jwillemsen** [comment]
Rebase done, just the changes made are part of this PR

**Comment by sloretz** [comment]
CI (packages up to rclcpp)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5977/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2494/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4937/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5860/)

**Comment by sloretz** [comment]
CI with a919f99
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5978/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2495/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4938/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5861/)

**Comment by sloretz** [comment]
Thanks for the PR

**Pull request merged**
