### PR TITLE
update topic information when entities go away

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by wjwwood** [comment]
> No description provided.

Can you explain what you've changed and why it's now possible? AFAIR, you didn't see anyway to accomplish this. What changed? I see you're comparing instance handles now, what was the issue before?

**Comment by dirk-thomas** [comment]
I got feedback from RTI on my question. Before I tried to use the `key` but that one was not the same when receiving invalid data. Another approach uses a not documented function but that didn't work for me either. Now it uses the instance handle instead.

Instance handles are not hashable which requires going to all and compare with each one. That makes the patch not very efficient for many topics.

**Comment by wjwwood** [comment]
+1

**Comment by jacquelinekay** [comment]
+1

As a side note, there is a large and growing amount of duplicated code between `rmw_connext_cpp` and `rmw_connext_dynamic_cpp`. Is a shared library that provides classes such as `CustomDataReaderListener` worthwhile?

**Comment by jacquelinekay** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
@jacquelinekay Sure, common code could be moved to a third package. Some of it might even be sharable between different vendors. There is also a lot of macro stuff in there which could be refactored...

**Pull request merged**
