### PR TITLE
readd typesupport check

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connects to ros2/ros2#30.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@esteve @tfoote @wjwwood Please review.

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
Same comment as opensplice (https://github.com/ros2/rmw_opensplice/pull/25#discussion_r28376507), but otherwise +1 if that is not possible.

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
+1

**Pull request merged**
