### PR TITLE
additional cmake logic to allow disabling one connext implementation or another

### PR DESCRIPTION
**Pull request by wjwwood**
Fixes ros2/ros2#147

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Does this allow you to reenable one rmw impl. using the environment variable after having it disabled before?

**Comment by wjwwood** [comment]
No, the logic to override the cache value with the environment was more complicated. I guess I could implement that, but I think it would be better to use the CMake cache variables at that point. The only reason I think we must have the the environment variables is so we can affect the farm without passing unused variables to all the other cmake packages (producing lots of unnecessary cmake warnings). These shouldn't be a problem when working locally, so I think the CMake variables should be used in that case.

**Comment by dirk-thomas** [comment]
Do we need the changes to `rmw_connext_shared_cpp`? Until now that package didn't need to know about which packages are using it. E.g. if someone adds a third rmw implementation this logic breaks. If someone wants to disables both he should just disabled Connext alltoget (e.g. not source Connext in the first place).

**Comment by wjwwood** [comment]
No, we can probably leave it out of this, but I was trying to avoid as much work as possible.

**Comment by dirk-thomas** [comment]
+1

**Pull request merged**
