### PR TITLE
Look for rtiddsgen2 as well as rtiddsgen

### PR DESCRIPTION
**Pull request by esteve**
This PR looks for `/usr/bin/rtiddsgen` in addition to `/usr/bin/rtiddsgen2`. Connext 5.2 provides the former, but not the latter.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Why do we need this beside #54?

**Comment by esteve** [comment]
@dirk-thomas because 5.1 crashes on my machine and I have to use 5.2, but #54 is not ready yet. And after all, this change is very minimal.

**Comment by dirk-thomas** [comment]
I triggered CI jobs for this branch and they failed:
http://ci.ros2.org/job/ros2_batch_ci_linux/173/
http://ci.ros2.org/job/ros2_batch_ci_osx/105/

**Comment by esteve** [comment]
PR was probably branched off a broken master, rebased to latest version.

**Comment by esteve** [comment]
New CI jobs:

http://ci.ros2.org/job/ros2_batch_ci_linux/175/
http://ci.ros2.org/job/ros2_batch_ci_osx/107/

**Comment by dirk-thomas** [comment]
lgtm

**Comment by tfoote** [comment]
+1

**Pull request merged**
