### PR TITLE
Don't use DURATION_INFINITE, it is a RTI specific

### PR DESCRIPTION
**Pull request by jwillemsen**
Issue #333

### CODE REVIEW

**Comment by clalancette** [comment]
@jwillemsen These PRs are very difficult to review.  I know you are probably working on all of them at the same time, but each PR should be an independent chunk that we can review.  For instance, it looks like only commit 35e43b6 is needed in this PR, and thus it is much easier to pull in the individual pieces if you make a branch with only that commit on it.  The same goes for the other PRs you have opened.

Doing it this way will ensure that we can start reviewing and getting some of the pieces in without necessarily pulling all of them in at the same time.  Thanks in advance.

**Comment by wjwwood** [comment]
Please instead Target this pull request at the branch for the other pull request. After it is merged you can change the target branch for this pr to be master again.

**Comment by wjwwood** [comment]
That's a fair point, I didn't consider that. I guess we'll have to merge them in order.

**Comment by sloretz** [comment]
@jwillemsen mind rebasing this PR?

**Comment by sloretz** [comment]
CI (packages up to rcl)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5995/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2504/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4948/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5871/)

**Comment by sloretz** [comment]
CI looks good, thanks for the PR

**Pull request merged**
