### PR TITLE
wrap Connext libraries in --no-as-needed

### PR DESCRIPTION
**Pull request by dirk-thomas**
Replaces #173, requires ament/ament_cmake#75.

### CODE REVIEW

**Comment by wjwwood** [comment]
I'm trying out a build on my Linux VM with this pr and https://github.com/ament/ament_cmake/pull/75, but do I need https://github.com/ros2/rcl/pull/61 too?

**Comment by dirk-thomas** [comment]
No, the `export_link_flags` is unrelated and should not be mixed.

With these two patches it should compile and link but the runtime behavior of Connext dynamic is still broken. Testing a patch for that right now.

**Comment by dirk-thomas** [comment]
At least it doesn't seem to break anything with the normal builds:

* http://ci.ros2.org/job/ci_linux/1616/
* http://ci.ros2.org/job/ci_osx/1220/
* http://ci.ros2.org/job/ci_windows/1581/

**Comment by wjwwood** [comment]
I'm retrying the build on my VM now.

**Comment by wjwwood** [comment]
Works for me.

**Comment by dirk-thomas** [comment]
Does that imply a +1 on the ament_cmake PR too?

**Comment by wjwwood** [comment]
Yeah, I think it's good to merge.

**Pull request merged**
