### PR TITLE
replace much of the macros in connext dynamic with templates

### PR DESCRIPTION
**Pull request by jacquelinekay**
Still in progress.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Any refactoring should only be considered when all the tests are actually enabled: ros2/system_tests#119

**Comment by jacquelinekay** [comment]
K, I think this is ready for review

http://ci.ros2.org/job/ci_linux/1341/
http://ci.ros2.org/job/ci_osx/1050/
http://ci.ros2.org/job/ci_windows/1354

**Comment by tfoote** [comment]
@ros2/ros2_team I installed the embeddable build status plugin. We can now have clearer statuss for builds by using the icons embeddable in github. 

Linux: [Build Status](http://ci.ros2.org/job/ci_linux/1341/)
OSX: [Build Status](http://ci.ros2.org/job/ci_osx/1050/)
Windows: [Build Status](http://ci.ros2.org/job/ci_windows/1353/)

Note I see one caveat which is that for a future build like the windows one it just seems to give the last result until the job is running.

**Comment by jacquelinekay** [comment]
[Build Status](http://ci.ros2.org/job/ci_windows/1359/)

This should fix the warnings on Windows. Several Connext Dynamic tests fail on Windows but the same is true on the nightly builds.

**Comment by jacquelinekay** [comment]
this one is close to ready. Using my c_parameters branch in rcl to test, there's some remaining issues with overwriting fields in nested messages.

**Comment by jacquelinekay** [comment]
Aforementioned issue with overwritten fields was fixed in 4fa617c

**Comment by dirk-thomas** [comment]
Can you please rewrite the commit history in a way which allows to distinguish moved code from actual code changes. Otherwise it is almost impossible to review this PR.

**Comment by jacquelinekay** [comment]
ok, I rewrote the history and started a new branch in #187. Closing this in favor of that.

**Pull request closed without merging**
